// <auto-generated />
using ECommerce.ProductService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.ProductService.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Kitchen"
                        });
                });

            modelBuilder.Entity("ECommerce.ProductService.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 10,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 25,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 30,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 15,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 20,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 50,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 35,
                            ReservedQuantity = 0
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 12,
                            ReservedQuantity = 0
                        });
                });

            modelBuilder.Entity("ECommerce.ProductService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "15-inch laptop with 16GB RAM and 512GB SSD",
                            ImageUrl = "https://placehold.co/600x400?text=Laptop",
                            Name = "Laptop",
                            Price = 75000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Android smartphone with 128GB storage",
                            ImageUrl = "https://placehold.co/600x400?text=Smartphone",
                            Name = "Smartphone",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Noise-cancelling wireless headphones",
                            ImageUrl = "https://placehold.co/600x400?text=Headphones",
                            Name = "Wireless Headphones",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "A book about writing clean and maintainable software",
                            ImageUrl = "https://placehold.co/600x400?text=Clean+Code",
                            Name = "Clean Code",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "A guide to becoming a better software developer",
                            ImageUrl = "https://placehold.co/600x400?text=Pragmatic+Programmer",
                            Name = "The Pragmatic Programmer",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Comfortable round-neck cotton T-shirt",
                            ImageUrl = "https://placehold.co/600x400?text=Cotton+T-Shirt",
                            Name = "Cotton T-Shirt",
                            Price = 800m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Lightweight shoes suitable for running and training",
                            ImageUrl = "https://placehold.co/600x400?text=Running+Shoes",
                            Name = "Running Shoes",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Automatic coffee maker for home use",
                            ImageUrl = "https://placehold.co/600x400?text=Coffee+Maker",
                            Name = "Coffee Maker",
                            Price = 3500m
                        });
                });

            modelBuilder.Entity("ECommerce.ProductService.Models.Inventory", b =>
                {
                    b.HasOne("ECommerce.ProductService.Models.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("ECommerce.ProductService.Models.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.ProductService.Models.Product", b =>
                {
                    b.HasOne("ECommerce.ProductService.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.ProductService.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.ProductService.Models.Product", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
